# Generated by Django 3.1.7 on 2021-03-11 09:56

# 3rd party
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IPAddr",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("continent_code", models.CharField(max_length=4)),
                ("continent_name", models.CharField(max_length=50)),
                ("country_code", models.CharField(max_length=4)),
                ("country_name", models.CharField(max_length=50)),
                ("region_code", models.CharField(max_length=4)),
                ("region_name", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                ("zip_code", models.CharField(max_length=15)),
                ("latitude", models.FloatField(max_length=20)),
                ("longitude", models.FloatField(max_length=20)),
            ],
        ),
    ]
