# Generated by Django 3.1.7 on 2021-03-11 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipaddr',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=15),
        ),
        migrations.AddField(
            model_name='ipaddr',
            name='url',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
