# Generated by Django 3.1.7 on 2021-03-11 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210311_1004'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IPAddr',
            new_name='IPAddress',
        ),
    ]
